// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thdsnenbeqlxdvviebie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoZHNuZW5iZXFseGR2dmllYmllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNTg3OTQsImV4cCI6MjA1ODYzNDc5NH0.4fbKmrSo50Lp_wbnA52Ok3XUJs2dOxnO-OQGu9PUh30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);